<div class="col-md-12">
    <div class="col-md-12 conteudo">

        <div class="col-md-5">
            <h2 class="titulo-pagina">Produtos</h2>
        </div>
        <div class="col-md-2" style="margin-bottom: 10px;">
            <a class="btn pull-right btn-success cadastrar-produto" href="/painel/produtos/cadastrar">
                <i class="fas fa-plus"></i> Cadastrar
            </a>
        </div>


        <table class="tabela-produtos table table-striped table-responsive-md">
            <thead>
            <tr>
                <th scope="col">Código</th>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
                <th scope="col">Valor</th>
                <th scope="col">Cadastrado</th>
                <th scope="col">Última Alteração</th>
                <th scope="col">Situação</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($produtos as $p): ?>
                <tr>
                    <th scope="row"><?= $p['id_produto'] ?></th>
                    <td><?= $p['nome'] ?></td>
                    <td><?= $p['descricao'] ?></td>
                    <td><?= $p['valor'] ?></td>
                    <td><?= date('d/m/Y H:i:s', strtotime($p['data_hora_cadastro'])) ?></td>
                    <td><?= date('d/m/Y H:i:s', strtotime($p['data_hora_alteracao'])) ?></td>
                    <td><?= $p['id_status'] ?></td>
                    <td>
                        <a class="btn btn-primary editar-produto"
                           href="/painel/produtos/editar?produto=<?= base64_encode($p['id_produto']) ?>">
                            <i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-danger excluir-produto"
                           data-id-produto="<?= base64_encode($p['id_produto']) ?>" href="#">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


